#include"elevator.h"
#include"egg.h"

DWORD WINAPI input(LPVOID lpParameter)
{  
	//全局变量的声明 
	extern int strategy; //服务策略：0是先来先服务，1是顺便服务；   
	extern struct passenger *callPtr;//存放用户请求的链表指针  
	extern char callrequest;
	extern int State;
	extern int IsSecond[];
	HANDLE hMutex;                   
 
	int request=0; 
 	double positionX=0, positionY=0;
         
    while(1){
	    WaitForSingleObject(hMutex,INFINITE);    //等待拿取钥匙 
	    
			 while(!(WaitForEvent() == KEYDOWN)) {}//若未遇到 KEYDOWN事件（键盘输入或者鼠标点击），则什么都不做。
             if(GetStruckKey() == VK_LBUTTON)//鼠标左键被按下
 			 {
             	positionX=GetMouseX();
         	    positionY=GetMouseY();
         	    
         	    //先来先服务策略 
  	            if(positionX>680&&positionX<783&&positionY>331&&positionY<434)
  	            {
  	            	prestrategy=strategy;
            	  	strategy=0;
            	  	SetActiveEgg(hEggs[6]);
            	  	ShowEgg(1);
            	  	SetActiveEgg(hEggs[7]);
            	  	ShowEgg(0);
           	    } 
				//顺便服务策略   	
       	        if(positionX>567&&positionX<670&&positionY>331&&positionY<434)
       	        {
       	        	prestrategy=strategy;
        	       	strategy=1;
        	       	SetActiveEgg(hEggs[7]);
            	  	ShowEgg(1);
            	  	SetActiveEgg(hEggs[6]);
            	  	ShowEgg(0);
       	        }
    			//内部请求  亮着的按钮为第24--32个egg。若开始为亮，则灭灯；若开始为灭，则亮灯。 
    			if(positionX>587&&positionX<650&&positionY>226&&positionY<289)//按钮1 
                {
                	callrequest='1';
                	SetActiveEgg(hEggs[24]);
                	if(IsSecond[24]==0)
            	    {
  	            	    ShowEgg(1);
  	            	    IsSecond[24]=1;
    	            }
            	  	else
            	  	{
	  	            	ShowEgg(0);
	  	            	IsSecond[24]=0;
	  	            }    
                }		        
                if(positionX>650&&positionX<713&&positionY>226&&positionY<289)//按钮2 
                {
                	callrequest='2';
                	SetActiveEgg(hEggs[25]);
                	if(IsSecond[25]==0)
            	    {
  	            	    ShowEgg(1);
  	            	    IsSecond[25]=1;
    	            }
            	  	else
            	  	{
	  	            	ShowEgg(0);
	  	            	IsSecond[25]=0;
	  	            }    
                }    
                if(positionX>713&&positionX<776&positionY>226&&positionY<289)//按钮3 
                {
                	callrequest='3';
                	SetActiveEgg(hEggs[26]);
                	if(IsSecond[26]==0)
            	    {
  	            	    ShowEgg(1);
  	            	    IsSecond[26]=1;
    	            }
            	  	else
            	  	{
	  	            	ShowEgg(0);
	  	            	IsSecond[26]=0;
	  	            }    
                }    
                if(positionX>587&&positionX<650&&positionY>163&&positionY<226)//按钮4 
                {
                	callrequest='4';
                	SetActiveEgg(hEggs[27]);
                	if(IsSecond[27]==0)
            	    {
  	            	    ShowEgg(1);
  	            	    IsSecond[27]=1;
    	            }
            	  	else
            	  	{
	  	            	ShowEgg(0);
	  	            	IsSecond[27]=0;
	  	            }    
                }    
                if(positionX>650&&positionX<713&&positionY>163&&positionY<226)//按钮5 
                {
                	callrequest='5';
                	SetActiveEgg(hEggs[28]);
            	  	if(IsSecond[28]==0)
            	    {
  	            	    ShowEgg(1);
  	            	    IsSecond[28]=1;
    	            }
            	  	else
            	  	{
	  	            	ShowEgg(0);
	  	            	IsSecond[28]=0;
	  	            }    
                }    
				if(positionX>713&&positionX<776&&positionY>163&&positionY<226)//按钮6 
                {
                	callrequest='6';
					SetActiveEgg(hEggs[29]);
            	  	if(IsSecond[29]==0)
            	    {
  	            	    ShowEgg(1);
  	            	    IsSecond[29]=1;
    	            }
            	  	else
            	  	{
	  	            	ShowEgg(0);
	  	            	IsSecond[29]=0;
	  	            }    
                }    
				if(positionX>587&&positionX<650&&positionY>100&&positionY<163)//按钮7 
                {
                    callrequest='7';
                    SetActiveEgg(hEggs[30]);
            	  	if(IsSecond[30]==0)
            	    {
  	            	    ShowEgg(1);
  	            	    IsSecond[30]=1;
    	            }
            	  	else
            	  	{
	  	            	ShowEgg(0);
	  	            	IsSecond[30]=0;
	  	            }    
                }    
				if(positionX>650&&positionX<713&&positionY>100&&positionY<163)//按钮8 
                {
                    callrequest='8';
                    SetActiveEgg(hEggs[31]);
            	  	if(IsSecond[31]==0)
            	    {
  	            	    ShowEgg(1);
  	            	    IsSecond[31]=1;
    	            }
            	  	else
            	  	{
	  	            	ShowEgg(0);
	  	            	IsSecond[31]=0;
	  	            }    
                }    
				if(positionX>713&&positionX<776&&positionY>100&&positionY<163)//按钮9 
                {
                	callrequest='9';
                	SetActiveEgg(hEggs[32]);
            	  	if(IsSecond[32]==0)
            	    {
  	            	    ShowEgg(1);
  	            	    IsSecond[32]=1;
    	            }
            	  	else
            	  	{
	  	            	ShowEgg(0);
	  	            	IsSecond[32]=0;
	  	            }    
                }
   				//外部上行请求   亮着的按钮为8--15个egg。若开始为亮，则灭灯；若开始为灭，则亮灯。 
				if(positionX>110&&positionX<138&&positionY>0&&positionY<39)//1层上行 
                {
                	callrequest='q';
                	SetActiveEgg(hEggs[15]);
            	  	if(IsSecond[15]==0)
            	    {
  	            	    ShowEgg(1);
  	            	    IsSecond[15]=1;
    	            }
            	  	else
            	  	{
	  	            	ShowEgg(0);
	  	            	IsSecond[15]=0;
	  	            }    
                }    
                if(positionX>110&&positionX<138&&positionY>56&&positionY<95)//2层上行 
                {
                	callrequest='w';
                	SetActiveEgg(hEggs[14]);
            	  	if(IsSecond[14]==0)
            	    {
  	            	    ShowEgg(1);
  	            	    IsSecond[14]=1;
    	            }
            	  	else
            	  	{
	  	            	ShowEgg(0);
	  	            	IsSecond[14]=0;
	  	            }    
                }    
				if(positionX>110&&positionX<138&&positionY>112&&positionY<151)//3层上行 
                {
                	callrequest='e';
                	SetActiveEgg(hEggs[13]);
            	  	if(IsSecond[13]==0)
            	    {
  	            	    ShowEgg(1);
  	            	    IsSecond[13]=1;
    	            }
            	  	else
            	  	{
	  	            	 ShowEgg(0);
	  	            	 IsSecond[13]=0;
	  	            }   
                }    
				if(positionX>110&&positionX<138&&positionY>171&&positionY<210)//4层上行 
                {
                	callrequest='r';
                	SetActiveEgg(hEggs[12]);
            	  	if(IsSecond[12]==0)
            	    {
  	            	    ShowEgg(1);
  	            	    IsSecond[12]=1;
    	            }
            	  	else
            	  	{
	  	            	ShowEgg(0);
	  	            	IsSecond[12]=0;
	  	            }    
                }    
			    if(positionX>110&&positionX<138&&positionY>226&&positionY<265)//5层上行 
			    {
                	callrequest='t';
                	SetActiveEgg(hEggs[11]);
            	  	if(IsSecond[11]==0)
            	    {
  	            	    ShowEgg(1);
  	            	    IsSecond[11]=1;
    	            }
            	  	else
            	  	{
	  	            	ShowEgg(0);
	  	            	IsSecond[11]=0;
	  	            }    
                }    
			    if(positionX>110&&positionX<138&&positionY>283&&positionY<322)//6层上行 
			    {
                	callrequest='y';
                	SetActiveEgg(hEggs[10]);
            	  	if(IsSecond[10]==0)
            	    {
  	            	    ShowEgg(1);
  	            	    IsSecond[10]=1;
    	            }
            	  	else
            	  	{
	  	            	 ShowEgg(0);
	  	            	 IsSecond[10]=0; 
	  	            }   
                }    
				if(positionX>110&&positionX<138&&positionY>340&&positionY<379)//7层上行 
				{
                	callrequest='u';
                	SetActiveEgg(hEggs[9]);
            	  	if(IsSecond[9]==0)
            	    {
  	            	    ShowEgg(1);
  	            	    IsSecond[9]=1;
    	            }
            	  	else
            	  	{
	  	            	 ShowEgg(0);
	  	            	 IsSecond[9]=0;
	  	            }   
                }    
				if(positionX>110&&positionX<138&&positionY>395&&positionY<434)//8层上行 
				{
                	callrequest='i';
                	SetActiveEgg(hEggs[8]);
            	  	if(IsSecond[8]==0)
            	    {
  	            	    ShowEgg(1);
  	            	    IsSecond[8]=1;
    	            }
            	  	else
            	  	{
	  	            	ShowEgg(0);
	  	            	IsSecond[8]=0;
	  	            }    
                }    
				//外部下行   亮着的按钮为16--23个egg。若开始为亮，则灭灯；若开始为灭，则亮灯。 
				if(positionX>138&&positionX<166&&positionY>60&&positionY<99)//2层下行 
				{
                	callrequest='a';
                	SetActiveEgg(hEggs[23]);
            	  	if(IsSecond[23]==0)
            	    {
  	            	    ShowEgg(1);
  	            	    IsSecond[23]=1;
    	            }
            	  	else
            	  	{
	  	            	ShowEgg(0);
	  	            	IsSecond[23]=0;
	  	            }    
                }    
				if(positionX>138&&positionX<166&&positionY>115&&positionY<154)//3层下行 
				{
                	callrequest='s';
                	SetActiveEgg(hEggs[22]);
            	  	if(IsSecond[22]==0)
            	    {
  	            	    ShowEgg(1);
  	            	    IsSecond[22]=1;
    	            }
            	  	else
            	  	{
	  	            	ShowEgg(0);
	  	            	IsSecond[22]=0;
	  	            }    
                }    
				if(positionX>138&&positionX<166&&positionY>172&&positionY<211)//4层下行 
				{
                	callrequest='d';
                	SetActiveEgg(hEggs[21]);
            	  	if(IsSecond[21]==0)
            	    {
  	            	    ShowEgg(1);
  	            	    IsSecond[21]=1;
    	            }
            	  	else
            	  	{
	  	            	ShowEgg(0);
	  	            	IsSecond[21]=0;
	  	            }    
                }    
				if(positionX>138&&positionX<166&&positionY>228&&positionY<267)//5层下行 
				{
                	callrequest='f';
                	SetActiveEgg(hEggs[20]);
            	  	if(IsSecond[20]==0)
            	    {
  	            	    ShowEgg(1);
  	            	    IsSecond[20]=1;
    	            }
            	  	else
            	  	{
	  	            	ShowEgg(0);
	  	            	IsSecond[20]=0;
	  	            }    
                }    
				if(positionX>138&&positionX<166&&positionY>284&&positionY<323)//6层下行 
				{
                	callrequest='g';
                	SetActiveEgg(hEggs[19]);
            	  	if(IsSecond[19]==0)
            	    {
  	            	    ShowEgg(1);
  	            	    IsSecond[19]=1;
    	            }
            	  	else
	  	            {
 	            	    ShowEgg(0);
 	            	    IsSecond[19]=0;
	  	            }
                }    
				if(positionX>138&&positionX<166&&positionY>342&&positionY<381)//7层下行 
				{
                	callrequest='h';
                	SetActiveEgg(hEggs[18]);
            	  	if(IsSecond[18]==0)
            	    {
  	            	    ShowEgg(1);
  	            	    IsSecond[18]=1;
    	            }
            	  	else{
	  	            	ShowEgg(0);
 	                    IsSecond[18]=0;
	  	            }
                }    
				if(positionX>138&&positionX<166&&positionY>396&&positionY<435)//8层下行 
				{
                	callrequest='j';
                	SetActiveEgg(hEggs[17]);
            	  	if(IsSecond[17]==0)
            	    {
  	            	    ShowEgg(1);
  	            	    IsSecond[17]=1;
    	            }
            	  	else{
	            	    ShowEgg(0);
	            	    IsSecond[17]=0;
	  	            }
                }    
				if(positionX>138&&positionX<166&&positionY>447&&positionY<485)//9层下行 
				{
                	callrequest='k';
                	SetActiveEgg(hEggs[16]);
            	  	if(IsSecond[16]==0)
            	    {
  	            	    ShowEgg(1);
  	            	    IsSecond[16]=1;
    	            }
            	  	else{
            	  		IsSecond[16]=0;
	  	            	ShowEgg(0);
	  	            }
            	  	    
                }   		    
				//关门键按下    
				if(positionX>709&&positionX<780&&positionY>14&&positionY<84)
				{

					    callrequest='#';
					    request=0;
			     }
				//将获得的鼠标位置置零   
                positionY=0;
             	positionX=0;
				switch(callrequest)
				{                     
					//将字符型请求转化成整型，方便后续程序运行 
					case'#':if(State==3)
                      	request=0;break;
            		case'1':request=1;break;
					case'2':request=2;break;
					case'3':request=3;break;
					case'4':request=4;break;
					case'5':request=5;break;
					case'6':request=6;break;
					case'7':request=7;break;
					case'8':request=8;break;
					case'9':request=9;break;
					case'Q':case'q':request=11;break;
            		case'W':case'w':request=12;break;
					case'E':case'e':request=13;break; 
					case'R':case'r':request=14;break;
            		case'T':case't':request=15;break;
					case'Y':case'y':request=16;break;
					case'U':case'u':request=17;break;
					case'I':case'i':request=18;break;
            		case'A':case'a':request=22;break;
		    		case'S':case's':request=23;break;
            		case'D':case'd':request=24;break;
	   	    		case'F':case'f':request=25;break;
            		case'G':case'g':request=26;break;
            		case'H':case'h':request=27;break;
            		case'J':case'j':request=28;break;
	        		case'K':case'k':request=29;break;
	        		default:request=0;break;
        		}
         }    
        //需要写入用户请求时      
        if(request!=0)
        {
            callPtr=malloc(sizeof(struct passenger)); //当有请求时，给头指针申请内存；       
        	if(callPtr!=NULL)//申请内存成功后 
        	{
       			callPtr->destination=request;             //将请求写入节点； 
				callPtr->nextPtr=NULL;  
				request=0;  
        	}
        }
             	
        ReleaseMutex(hMutex);                         //释放线程，交还钥匙 
	}
}
